### ISSUE TITLE
Breaks editable fields, possibly other things?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy-relations#1]
I was having the following issue with the editable fields package:
https://github.com/JackAdams/meteor-editable-text/issues/43#issuecomment-139690678

It turned out to be related to the astronomy relations package. The author had the following to say:
"Okay jagi:astronomy-relations messes pretty fundamentally with the data returned with findOne. I'm kind of surprised that the correct text even shows at all for those editable fields."

I realize that this is  pretty much not even a beta-stage package yet, but I thought I'd bring it to your attention in case it would change the way any features are implemented.

**Comment by lukejagodzinski** [comment]
Hi, thanks for letting me know. However could you describe this problem in more details?

Yes, relations package is its early stage. I don't encourage to use it at all at this stage. It was more like experiment that has to be evolved. What I know for sure, currently it has error with caching. When relation is retrieved it's cached and does not track changes, so maybe it's why you had problems with it.

However, I would be glad if you could describe your problem because the discussion under the link you posted does not mention it directly.

**Comment by lukejagodzinski** [comment]
If it goes about the `_original` context, it has to be done because of an assumption that fields' values resides directly in the document you fetched from the collection using the `findOne()` method. It isn't true in current version. However, it will be changed in the 1.0 version of Astronomy, so you won't have to do that.

**Comment by JulianKingman** [comment]
OK, cool.

So the problem was that when I edited an editable text field it gave me the error mentioned in the discussion and wouldn't save:
`Exception while simulating the effect of invoking '_editableTextWrite' M…r.m…e.errorClass {message: "Match error: Expected plain object", path: "", sanitizedError: M…r.m…e.errorClass, errorType: "Match.Error"} Error: Match error: Expected plain object at checkSubtree`
etc...
In the meteorpad (http://meteorpad.com/pad/zKDKhqzuL7FnnPj86/Editable%20Text%20Debug), I managed to reduce the problem to the relations package.

Is there anything else that would be helpful to clarify?

**Comment by lukejagodzinski** [comment]
Ok I've investigated the `editableText` package and the problem is on their side. They assume that object passed to the `editableText` helper is a plain JavaScript object but it's not. This assumption is wrong.

However, you can overcome this inconvenience and do something like this:

``` hb
{{#with source.get()}}
  <h1>{{> editableText collection="sources" field="title"}}</h1>
  <div>{{> editableText collection="sources" field="edition"}}</div>
  <h4>{{_id}}</h4>
{{/with}}
```

As you can see instead the `source` context I've used `source.get()` which gets plain JavaScript object.

**Comment by JulianKingman** [comment]
Thanks, I passed on your feedback to the developer.
